---
pipeline:
  docker-publish-master:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: rancherlabs/website-theme
    context: .
    tag: latest
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: push
